// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbX6UeIVmoF9GAEf2U4WBC9KPpp0svvOM',
    appId: '1:498466262519:web:e0046268134063f2ef72f2',
    messagingSenderId: '498466262519',
    projectId: 'advmobprog-firebase-6a5bf',
    authDomain: 'advmobprog-firebase-6a5bf.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-6a5bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAha5Df2q-MkHAJwVGA6SSWttcFCs4hY-w',
    appId: '1:498466262519:android:7f3f7e9720a879a9ef72f2',
    messagingSenderId: '498466262519',
    projectId: 'advmobprog-firebase-6a5bf',
    storageBucket: 'advmobprog-firebase-6a5bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwURh7kvTge8k_OvBV59qTBJ_daCuB0cQ',
    appId: '1:498466262519:ios:6f930b07b4b1886cef72f2',
    messagingSenderId: '498466262519',
    projectId: 'advmobprog-firebase-6a5bf',
    storageBucket: 'advmobprog-firebase-6a5bf.firebasestorage.app',
    iosBundleId: 'com.example.padillaAdvmobprog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbX6UeIVmoF9GAEf2U4WBC9KPpp0svvOM',
    appId: '1:498466262519:web:74c395b1f9627885ef72f2',
    messagingSenderId: '498466262519',
    projectId: 'advmobprog-firebase-6a5bf',
    authDomain: 'advmobprog-firebase-6a5bf.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-6a5bf.firebasestorage.app',
  );
}
